plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc1 pc2 pc3 pc4 pc5 pc6) (Att > att1 att2 att3 att4) (DL > dl1 dl2 dl3 dl4 dl5 dl6 dl7) (Fam > fam1 fam2 fam3) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam)
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl4 dl5 dl6) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) correlate(mv lv cross, cutoff(0.3))
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl4 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) correlate(mv lv cross, cutoff(0.3))
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) correlate(mv lv cross, cutoff(0.3))
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) group(female)
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) group(age45)
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) group(stem)
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) group(tenure)
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) group(phd)
plssem (PSPA > pspa1 pspa2 pspa3) (PC > pc2 pc3 pc4) (Att > att1 att2 att3) (DL > dl2 dl3 dl5) (Fam > fam1 fam2) (AoSPS > k a b), structural(AoSPS PSPA PC Att DL Fam) group(inexperienced)
